name: test

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.15.4
          - 17.x
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Run tests
        run: npm test
        env:
          MAILTRAP_SMTP_HOST: smtp.mailtrap.io
          MAILTRAP_USERNAME: ${{ secrets.MAILTRAP_USERNAME }}
          MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
          MAILTRAP_EMAIL: ${{ secrets.MAILTRAP_EMAIL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FROM_EMAIL: virk@adonisjs.com
          MAILGUN_ACCESS_KEY: ${{ secrets.MAILGUN_ACCESS_KEY }}
          MAILGUN_BASE_URL: https://api.mailgun.net/v3
          SPARKPOST_API_KEY: ${{ secrets.SPARKPOST_API_KEY }}
